#Port settings :
server.port=8080

#Kafka configuration :
spring.kafka.bootstrap-servers=192.168.31.112:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=metrics-consumer-group
